import 'package:flutter/widgets.dart';
import 'package:yod_nak_ram_ui_kit/src/themes/text_styles/ram_text_style.dart';
import 'package:yod_nak_ram_ui_kit/src/themes/text_styles/text_style_tokens.dart';

final ramThTextStyle = RamTextStyle(
  displayLarge: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale14,
    height: kLineHeight14 / kFontScale14,
    letterSpacing: kLetterSpacing5,
  ),
  displayMedium: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale13,
    height: kLineHeight13 / kFontScale13,
    letterSpacing: kLetterSpacing5,
  ),
  displaySmall: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale12,
    height: kLineHeight12 / kFontScale12,
    letterSpacing: kLetterSpacing5,
  ),
  headlineLarge: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale11,
    height: kLineHeight11 / kFontScale11,
    letterSpacing: kLetterSpacing4,
  ),
  headlineMedium: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale10,
    height: kLineHeight10 / kFontScale10,
    letterSpacing: kLetterSpacing4,
  ),
  headlineSmall: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight3,
    fontSize: kFontScale9,
    height: kLineHeight9 / kFontScale9,
    letterSpacing: kLetterSpacing4,
  ),
  titleLarge: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight3,
    fontSize: kFontScale8,
    height: kLineHeight8 / kFontScale8,
    letterSpacing: kLetterSpacing3,
  ),
  titleMedium: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale7,
    height: kLineHeight7 / kFontScale7,
    letterSpacing: kLetterSpacing3,
  ),
  titleSmall: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale6,
    height: kLineHeight6 / kFontScale6,
    letterSpacing: kLetterSpacing3,
  ),
  bodyLarge: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale5,
    height: kLineHeight5 / kFontScale5,
    letterSpacing: kLetterSpacing3,
  ),
  bodyLargeExtraThin: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight1,
    fontSize: kFontScale5,
    height: kLineHeight5 / kFontScale5,
    letterSpacing: kLetterSpacing3,
  ),
  bodyLargeExtraBold: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight3,
    fontSize: kFontScale5,
    height: kLineHeight5 / kFontScale5,
    letterSpacing: kLetterSpacing3,
  ),
  bodyMediumExtraThin: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight1,
    fontSize: kFontScale4,
    height: kLineHeight4 / kFontScale4,
    letterSpacing: kLetterSpacing2,
  ),
  bodyMedium: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale4,
    height: kLineHeight4 / kFontScale4,
    letterSpacing: kLetterSpacing2,
  ),
  bodySmall: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale3,
    height: kLineHeight3 / kFontScale3,
    letterSpacing: kLetterSpacing2,
  ),
  labelLarge: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight1,
    fontSize: kFontScale3,
    height: kLineHeight2 / kFontScale3,
    letterSpacing: kLetterSpacing1,
  ),
  labelMedium: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale2,
    height: kLineHeight2 / kFontScale2,
    letterSpacing: kLetterSpacing1,
  ),
  labelSmall: TextStyle(
    //fontFamily: 'DB Heavent Now Std',
    fontWeight: kFontWeight2,
    fontSize: kFontScale1,
    height: kLineHeight1 / kFontScale1,
    letterSpacing: kLetterSpacing1,
  ),
);
